import type { DashboardWidgetLayout } from '../models/dashboard-layout.model';

export const HOME_DASHBOARD_LAYOUT: DashboardWidgetLayout[] = [
  {
    id: 'income-goal',
    x: 0,
    y: 0,
    cols: 12,
    rows: 2,
    minItemCols: 6,
    minItemRows: 2,
    maxItemRows: 3,
  },
  {
    id: 'portfolio-growth',
    x: 0,
    y: 2,
    cols: 6,
    rows: 4,
    minItemCols: 4,
    minItemRows: 3,
    maxItemRows: 6,
  },
  {
    id: 'dividend-calendar',
    x: 6,
    y: 2,
    cols: 6,
    rows: 4,
    minItemCols: 4,
    minItemRows: 3,
    maxItemRows: 6,
  },
  {
    id: 'asset-allocation',
    x: 0,
    y: 6,
    cols: 5,
    rows: 3,
    minItemCols: 4,
    minItemRows: 2,
    maxItemRows: 5,
  },
  {
    id: 'top-holdings',
    x: 5,
    y: 6,
    cols: 7,
    rows: 3,
    minItemCols: 4,
    minItemRows: 2,
    maxItemRows: 5,
  },
  {
    id: 'milestones',
    x: 0,
    y: 9,
    cols: 6,
    rows: 3,
    minItemCols: 4,
    minItemRows: 2,
    maxItemRows: 5,
  },
  {
    id: 'alerts',
    x: 6,
    y: 9,
    cols: 6,
    rows: 2,
    minItemCols: 4,
    minItemRows: 2,
    maxItemRows: 4,
  },
  {
    id: 'explore',
    x: 0,
    y: 11,
    cols: 12,
    rows: 2,
    minItemCols: 6,
    minItemRows: 2,
    maxItemRows: 4,
  },
];
