import { StockSuggestion } from '../models/stock-search.model';

export const POPULAR_STOCKS: StockSuggestion[] = [
  { symbol: 'AAPL', name: 'Apple Inc', type: 'Common Stock' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', type: 'Common Stock' },
  { symbol: 'GOOGL', name: 'Alphabet Inc', type: 'Common Stock' },
  { symbol: 'AMZN', name: 'Amazon.com Inc', type: 'Common Stock' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', type: 'Common Stock' },
  { symbol: 'META', name: 'Meta Platforms Inc', type: 'Common Stock' },
  { symbol: 'TSLA', name: 'Tesla Inc', type: 'Common Stock' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', type: 'Common Stock' },
  { symbol: 'KO', name: 'The Coca-Cola Company', type: 'Common Stock' },
  { symbol: 'PG', name: 'Procter & Gamble Co', type: 'Common Stock' },
  { symbol: 'PEP', name: 'PepsiCo Inc', type: 'Common Stock' },
  { symbol: 'V', name: 'Visa Inc', type: 'Common Stock' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co', type: 'Common Stock' },
  { symbol: 'O', name: 'Realty Income Corporation', type: 'REIT' },
  { symbol: 'SCHD', name: 'Schwab US Dividend Equity ETF', type: 'ETF' },
  { symbol: 'VYM', name: 'Vanguard High Dividend Yield ETF', type: 'ETF' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', type: 'ETF' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', type: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', type: 'ETF' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc', type: 'Common Stock' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', type: 'Common Stock' },
  { symbol: 'ABBV', name: 'AbbVie Inc', type: 'Common Stock' },
  { symbol: 'T', name: 'AT&T Inc', type: 'Common Stock' },
  { symbol: 'VZ', name: 'Verizon Communications', type: 'Common Stock' },
  { symbol: 'MAIN', name: 'Main Street Capital Corporation', type: 'Common Stock' },
];
