export const STOCK_SECTORS: Record<string, string> = {
  AAPL: 'Technology',
  MSFT: 'Technology',
  GOOGL: 'Technology',
  GOOG: 'Technology',
  AMZN: 'Consumer Cyclical',
  NVDA: 'Technology',
  META: 'Technology',
  TSLA: 'Consumer Cyclical',
  JNJ: 'Healthcare',
  KO: 'Consumer Defensive',
  PG: 'Consumer Defensive',
  PEP: 'Consumer Defensive',
  V: 'Financial Services',
  JPM: 'Financial Services',
  O: 'Real Estate',
  SCHD: 'ETF / Fund',
  VYM: 'ETF / Fund',
  SPY: 'ETF / Fund',
  QQQ: 'ETF / Fund',
  VTI: 'ETF / Fund',
  'BRK.B': 'Financial Services',
  BRK: 'Financial Services',
  XOM: 'Energy',
  ABBV: 'Healthcare',
  T: 'Communication Services',
  VZ: 'Communication Services',
  MAIN: 'Financial Services',
  WMT: 'Consumer Defensive',
  HD: 'Consumer Cyclical',
  MCD: 'Consumer Cyclical',
  UNH: 'Healthcare',
  LLY: 'Healthcare',
  MRK: 'Healthcare',
  PFE: 'Healthcare',
  COST: 'Consumer Defensive',
  AVGO: 'Technology',
  AMD: 'Technology',
  INTC: 'Technology',
  CRM: 'Technology',
  NKE: 'Consumer Cyclical',
  DIS: 'Communication Services',
  BA: 'Industrials',
  CAT: 'Industrials',
  CVX: 'Energy',
  COP: 'Energy',
  NEE: 'Utilities',
  DUK: 'Utilities',
  SO: 'Utilities',
  MO: 'Consumer Defensive',
  PM: 'Consumer Defensive',
  CL: 'Consumer Defensive',
  MMM: 'Industrials',
  IBM: 'Technology',
  CSCO: 'Technology',
  ORCL: 'Technology',
  ADBE: 'Technology',
  PYPL: 'Financial Services',
  MA: 'Financial Services',
  BAC: 'Financial Services',
  WFC: 'Financial Services',
  GS: 'Financial Services',
  MS: 'Financial Services',
  LOW: 'Consumer Cyclical',
  SBUX: 'Consumer Cyclical',
  TGT: 'Consumer Cyclical',
  UPS: 'Industrials',
  FDX: 'Industrials',
  LMT: 'Industrials',
  RTX: 'Industrials',
  DE: 'Industrials',
  HON: 'Industrials',
  LIN: 'Basic Materials',
  APD: 'Basic Materials',
  NEM: 'Basic Materials',
  FCX: 'Basic Materials',
  AMGN: 'Healthcare',
  GILD: 'Healthcare',
  BMY: 'Healthcare',
  TMO: 'Healthcare',
  DHR: 'Healthcare',
  ISRG: 'Healthcare',
  CMCSA: 'Communication Services',
  TMUS: 'Communication Services',
  CHTR: 'Communication Services',
  PLD: 'Real Estate',
  AMT: 'Real Estate',
  EQIX: 'Real Estate',
  SPG: 'Real Estate',
  DLR: 'Real Estate',
  VNQ: 'ETF / Fund',
  JEPI: 'ETF / Fund',
  JEPQ: 'ETF / Fund',
  DIVO: 'ETF / Fund',
  DGRO: 'ETF / Fund',
  HDV: 'ETF / Fund',
  NOBL: 'ETF / Fund',
};

export function getSectorForTicker(ticker: string): string {
  return STOCK_SECTORS[ticker.toUpperCase()] ?? 'Other';
}
